baseURL: "https://jailaniteach.github.io"
languageCode: "en-us"
title: "Jailani Rahman"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 20
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: logs
      name: Teaching Practice Logs
      title: Teaching Practice Logs
      url: /logs
      weight: 1
    - identifier: module
      name: Module Details
      title: Teaching Practice Module Details
      url: /logs/module
      parent: logs
      weight: 1
    - identifier: weekly
      name: Weekly Records
      title: Teaching Practice Weekly Records
      url: /logs/weekly
      parent: logs
      weight: 2
    - identifier: observation
      name: Observation Feedbacks
      title: Teaching Practice Observation Feedbacks
      url: /logs/observation
      parent: logs
      weight: 3
    - identifier: activities
      name: School Activities
      title: School Activities
      url: /logs/activities
      parent: logs
      weight: 4
    - identifier: reflections
      name: Weekly Reflections
      title: Weekly Reflections
      url: /logs/reflections
      parent: logs
      weight: 5
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Jailani Rahman"
  description: ""
  # staticPath: ""  # The path to serve the static files from
  favicon: "/fav.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark" # light, dark

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  color:
    textColor:
    secondaryTextColor:
    backgroundColor:
    secondaryBackgroundColor:
    primaryColor:
    secondaryColor:

    darkmode:
      textColor: "#F5F5F5"
      secondaryTextColor: "#F5F5F5"
      backgroundColor: "#313552"
      primaryColor: "#F1E0AC"
      secondaryColor: "#30475E"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Jailani Rahman" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: "E-portfolio page for"
    title: "Jailani Rahman."
    subtitle: "Educator. Software Developer."
    content: ""
    image: /images/me.jpg
    bottomImage:
      enable: false
    # roundImage: true # Make hero image circular | default false
    button:
      enable: false
      name: "Teaching Logs"
      url: "/logs"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/jailanihar
        - icon: fab fa-twitter
          url: https://twitter.com/jailanihar
        - icon: fab fa-linkedin
          url: https://www.linkedin.com/in/jailani-rahman-3b264564/
        - icon: fa fa-envelope
          url: "mailto:22070309f@student.ibte.edu.bn"

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/avatar.jpg"
    content: |-
      Welcome to my e-portfolio profile page. My name is Mohammad Jailani Haji Abdul Rahman, I am an educator with 9 years of experience in teaching computer subjects at Mechanical Training Centre, Department of Technical Education (2014-2015) and School of Information and Communication Technology (SICT), Politeknik Brunei (2015-present).
      
      I am passionate about trying new things related to software development and technologies, and eager to share those knowledge with students. I am a type that always persistence towards solving challenges that I encountered.
      
      I always believe in learning by doing and I would like to give students ample experiences on the topic that I am teaching. Through these experiences, I believe students will have the competencies needed to succeed in the field at the same time providing them with the tools, resources and preparing them with necessary 21st century skills.

      Even with my 9 years of teaching experience, I believe there are still much to learn.
      
      To further enrich my teaching capabilities, I am currently enrolled to a teaching training programme full-time which is Diploma in Technical Education at TVET Academy, Institute of Brunei Technical Education as an in-service trainee.
      
      This e-portfolio site includes my teaching experience and reflection during my teaching practice as part of completion requirement for Diploma in Technical Education and what activities I am involve in.
      
      For my teaching practice, I am teaching for a whole semester module Network Programming for SICT that is offered on semester 4 of their Diploma Level 5 in IT Network programme.

    skills:
      enable: false
      title: "Here are a few technologies I've been working with recently:"
      items:
        - "HTML"
        - "CSS"
        - "JavaScript"
        - "PHP"
        - "Laravel"
        - "MySQL"
        - "Java"
        - "Spring Framework"

  # Experience
  experience:
    enable: true
    title: "Work experiences and subjects taught"
    items:
      - job: "Education Officer"
        company: "Politeknik Brunei"
        companyUrl: "https://pb.edu.bn/"
        date: "July 2015 - Present"
        info:
          enable: false
        featuredLink:
          enable: false
          url: "https://example.com"
        content: |
          I taught in School of Information and Communication Technology. The followings are the qualifications and the subjects that I taught:

          - Advanced Diploma
            - Database Management Systems
            - Advanced Programming
          - Diploma Level 5
            - Programming Application
            - Python Programming
            - Object Oriented Programming
            - Advanced Programming
            - Network Programming

          I have taught students on how to:
          - design and implement relational database systems in MySQL
          - program using Java programming language procedurally, object oriented, event driven to create console applications, desktop applications (using Swing and JavaFX library), web applications (using Spring Framework with Thymeleaf), database applications (using JDBC and Hibernate) and applications that communicate through network.
          - program using Python programming language procedurally and object oriented to create console application for data analytics using NumPy and pandas.
      
      - job: "Senior Technical Instructor"
        company: "Department of Technical Education"
        companyUrl: "https://ibte.edu.bn/"
        date: "March 2014 - June 2015"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I taught in Mechanical Training Centre. The followings are the qualifications and the subjects that I taught:

          - Industrial Skills Qualification
            - Numeracy
            - Applied IT
          - Skills Certificate 2
            - IT Applications
          - Skills Certificate 3
            - Mathematics
          - National Diploma
            - IT Applications

          I have taught students on how to use Microsoft Office Applications (Word, Excel, Powerpoint, Publisher and Access)
  
  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Diploma in Technical Education"
        school:
          name: "Institute of Brunei Technical Education, Brunei Darussalam"
          url: "https://ibte.edu.bn/"
        date: "2022 - Present"
        GPA: "Pending"
        content: |-

      - title: "Master of Science in Advanced Computation Methods"
        school:
          name: "University of Leicester, United Kingdom"
          url: "https://le.ac.uk/"
        date: "2012 - 2013"
        GPA: "Merit"
        content: |-

      - title: "Bachelor of Science (Honours) in Computing Science (Software Engineering)"
        school:
          name: "University of Newcastle upon Tyne, United Kingdom"
          url: "https://ncl.ac.uk/"
        date: "2010 - 2012"
        GPA: "Second Class Upper Honours"
        content: |-

      - title: "Higher National Diploma in Business Software Development"
        school:
          name: "University of Bolton, United Kingdom"
          url: "https://www.bolton.ac.uk/"
        date: "2008 - 2010"
        GPA: "2.67 GPA"
        content: |-

  # Achievements
  achievements:
    enable: true
    # title: "Custom Name"
    items:
      - title: IBTE ICT Taskforce
        content: Involved in a committee overseeing the analysis and implementation of IT infrastructure needs for Department of Technical Education representing Mechanical Training Centre where the committee managed to acquired computers and printers for staffs, improved network infrastructure and improved video surveillance across the school.
      - title: Politeknik Brunei's Admission System
        content: Involved in a team to develop and deliver Politeknik Brunei's admission system where my role is as a full-stack developer.

  # projects
  projects:
    enable: false
    # title: "Custom Name"
    items:
      - title: Hugo Profile
        content: A highly customizable and mobile first Hugo template for personal portfolio and blog.
        image: /images/projects/profile.png
        featured:
          name: Demo
          link: https://hugo-profile.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fa fa-envelope
            url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/gurusabarish/hugo-profile
          - icon: fab fa-twitter
            url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Image Converter
        content: A web app to convert image to pdf, png to jpg, png to jpg and png to webp without database using django.
        image: /images/projects/converter.jpg
        featured:
          name: Demo
          link: https://django-converter.herokuapp.com
        badges:
          - "Django"
          - "Bootstrap"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/converter

      - title: Hugo Profile V2
        content: A clean and simple Hugo template for personal portfolio and blog.
        image: /images/projects/profile2.jpg
        featured:
          name: Demo V2
          link: https://hugo-profile-2.netlify.app
        badges:
          - "Hugo"
          - "Bootstrap"
          - "Javascript"
        links:
          - icon: fab fa-github
            url: https://github.com/gurusabarish/HugoProfileV2

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: My inbox is always open. Whether you have a question or just want to say hi, Iâ€™ll try my best to get back to you!
    email: 22070309f@student.ibte.edu.bn
    btnName: Mail me
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"

  footer:
    recentPosts:
      path: "logs"
      count: 6
      title: Teaching Practice Logs
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/jailanihar
      linkedin: https://linkedin.com/in/jailani-rahman-3b264564/
      twitter: https://twitter.com/jailanihar

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"